#+STARTUP: showall

* site-template

A template for a site that was intended to include the following:
- Ring/Compojure-centric project structure and routing handling.  (Started)
- A few test endpoints.  (Started)
- The [[http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded][reloaded workflow]].
- Monger integration with at least some basic CRUD.
- Spring Security integration.  (Started)
- Role-based access rules.  (Not done)
- Email (just drop in email.clj).
- Crypto (just drop in crypto.clj).
- Unit tests.  (Not done)
- A test index.html page.
- Architecture-level macros, if any.  (Started)

While a fully working template, this is only partially complete by the feature
list above.  I migrated this over to a private repo after getting it to its
current state, but perhaps something done here so far can be of informative
value to others.


** Usage

Edit config.clj to set MongoDB settings.

Then to run the data generator:

#+BEGIN_SRC sh
lein repl :headless
#+END_SRC

Connect to the running application and in a REPL buffer run:

#+BEGIN_SRC clojure
(boot)
#+END_SRC

Since this project implements a customized version of the "reloaded" workflow,
you can reset everything (including server settings) without restarting the
REPL by running:

#+BEGIN_SRC sh
(refresh)
(reset)
#+END_SRC

Currently, you'll need to evaluate the security.clj file first though.  To do
so, open it and eval it with C-c C-l <Enter>.

If you ever get into a state where the project didn't reload completely due to
an error, run this once you've fixed the error:

#+BEGIN_SRC clojure
(clojure.tools.namespace.repl/refresh)
#+END_SRC


** Under Consideration

Some other things to consider are:
- [[https://github.com/clojure/test.check][test.check]]
- [[http://clojure-liberator.github.io/][Liberator]]
